# Generated by Django 4.0.1 on 2022-01-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/default_course_image.png', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
